<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-02-13 05:57
=======
# Generated by Django 6.0.1 on 2026-02-13 04:10
>>>>>>> a6bdc79cd37d9f41c0c8d9bf6bf73f5d150c4e51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='waterbottle',
<<<<<<< HEAD
            old_name='sku',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='currentquant',
            new_name='current_quantity',
=======
            old_name='currentquant',
            new_name='Current_Quantity',
>>>>>>> a6bdc79cd37d9f41c0c8d9bf6bf73f5d150c4e51
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='mouthsize',
<<<<<<< HEAD
            new_name='mouth_size',
=======
            new_name='Mouth_Size',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='sku',
            new_name='SKU',
>>>>>>> a6bdc79cd37d9f41c0c8d9bf6bf73f5d150c4e51
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='supplier',
            new_name='supplied_by',
        ),
    ]
